{% set name = "dyntapy" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dyntapy-{{ version }}.tar.gz
  sha256: 09a46766d6d2dfeba1c3bc5a7f5c27a3c2363bdea158350fab8de0b359dc055e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numba >=0.55
    - bokeh >=3.0
    - osmnx >=1.3
    - pandas
    - scipy
    - numpy
    - geojson
    - pyyaml
    - networkx >=2.7
    - pyproj
    - geopandas
    - shapely
    - matplotlib-base
    - notebook
    - setuptools

test:
  imports:
    - dyntapy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.kuleuven.be/ITSCreaLab/public-toolboxes/dyntapy
  summary: Macroscopic Static and Dynamic Traffic Assignment in Python
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - JeroenVerstraete
    - p-ortmann
